name: Gradle build

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Type of tests (regresion/humo)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: gradle clean test -PincludeTags="${{{github.event.inputs.test-type}}" aggregate
        continue-on-error: true
      - name: Publicar informes de Serenity
        uses: actions/upload-artifact@v2
        with:
          name: serenity-reports
          path: target/site/serenity/index.html


